apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-info
  labels:
    app: movie-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-info
  template:
    metadata:
      labels:
        app: movie-info
    spec:
      containers:
      - name: movie-info
        image: atosci/movieinfo
        ports:
        - containerPort: 80
