apiVersion: v1
kind: Service
metadata:
  name: movie-info
  labels:
    app: movie-info
spec:
  name: movie-info
  selector:
    app: movie-info
  ports:
    protocol: TCP
    port: 80
    targetport: http
